# Generated by Django 5.0.6 on 2024-09-07 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0003_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 31, 32, 841610)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 31, 32, 841610)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 31, 32, 840613)),
        ),
    ]
