# Generated by Django 5.0.6 on 2024-09-07 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0004_sales_customer_name_alter_deffered_payments_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer_name',
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 35, 11, 984648)),
        ),
        migrations.AlterField(
            model_name='deffered_payments',
            name='date_of_payment',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 35, 11, 984648)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 7, 19, 35, 11, 984648)),
        ),
    ]
