# Generated by Django 5.0.6 on 2024-09-16 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgl_app', '0008_receipt_alter_sales_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
        migrations.AddField(
            model_name='sales',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
